### ISSUE TITLE
Add version independent link for backlinking (canonical link)

### ISSUE THREAD

**Issue by richierocks** [datacamp/RDocumentation-app#268]
For providing permanent links to RDcoumentation pages, it is useful to be able to easily give a version-independent link.  For example, if I want to demonstrate an R function in an answer on StackOverflow, I can link to RDocumentation, but I don't want to link to a version based upon a specific version of a package &ndash; I want to give a link to whatever the current version is.

For example, I want to link to

https://www.rdocumentation.org/packages/base/topics/paste

not 

https://www.rdocumentation.org/packages/base/versions/3.3.1/topics/paste

This is currently possible, but fiddly since it involves copying the URL, then manually editing it.

It would be useful to have a some text near the top of the help page that states 

```
If you want to provide a permanent link to this function, link to  
https://www.rdocumentation.org/packages/thispkg/topics/thisfn
```

Maybe with a "Copy the link" button too.

**Comment by richierocks** [comment]
On further thought, the link target should probably be to

https://www.rdocumentation.org/link/thisfn?package=thispkg

**Comment by ludov04** [comment]
@richierocks I think that this one: 
https://www.rdocumentation.org/packages/base/topics/paste
makes more sense because the `/link/...` endpoint is actually to dynamically resolve the links that we find in the packages and topics pages, thoses links are from the `\link{}` macro in the Rd files and we cannot resolve them at "parse" time.

cc @ddmkr 
What do you think about displaying a http://fontawesome.io/icon/link/ icon beside the package/topic title with a tooltip saying Copy link, when the user clicks on it, the version independant link would be copied to his clipboard

**Comment by filipsch** [comment]
cc @martijnsublime @dwaynemartin if we fix this, this meets the request for a canonical link.

**Comment by filipsch** [comment]
@ludov04 proposal for putting it in there.
Disclaimer: very little inspiration...
https://www.dropbox.com/s/xll41pczufuanxt/rdocs_specs.pdf?dl=0
