### ISSUE TITLE
Bring RDocumentation to Dash

### ISSUE THREAD

**Issue by MrLoh** [datacamp/RDocumentation-app#68]
Would it be possible to bring this awesome project to [Dash](https://kapeli.com/dash). Dash is a really awesome way to browse docsets and RDocumentation is definitely the best (and pretty much only) good ressource to browse R docsets. 

It's possible to contribute HTML Docsets as described here. 
https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset

I'd love to help with making this happen, but getting some input on the feasability from someone who is developing that would be great.

**Comment by ludov04** [comment]
Hi @MrLoh,
sorry for the long delay.
After investigating the feasibility of this, we are afraid it's gonna be too complex to put in place. 
Dash is great but it requires that the docset can be browsable offline so all documentation should be static and embedded into the docset.
RDocumentation features more than `10.000` packages and more than `1.500.000` topic pages.
Github, CRAN and Bioconductor are crawled everyday to search for new versions of packages and update the documentation, which makes RDocumentation very dynamic.

Rendering that amount of pages and making it into a static docset while making sure everything is up to date will requires a great amount of infrastructure work and processing..

Thanks for the good suggestion though.

**Comment by retrography** [comment]
Hi @ludov04,

Sorry to bother again on the closed topic, but it seems to me your approach to the issue is not right. Of course, compiling offline versions of all R docs in real time is an unsurmountable task. But that is absolutely not needed. Dash generates many of its docsets on the fly and from the source material. For instance, it allows you to get the docs for any Ruby or Java package you like, as it includes an embedded converter. All we need to do is to create this embedded converter for R docs, and then the documents will be converted upon download. 

To do that, we need to get in touch with @Kapeli, of course. But he has shown to be an open person in general, and he has even posted [his Javadoc converter as an example](https://github.com/Kapeli/javadocset).

**Comment by Kapeli** [comment]
Ruby Gems and PHP Packages are the only ones that are generated from source. All others are generated by downloading the docs from a third party service and turning those docs into a docset (i.e. no source involved).

Generating docs from source is quite error-prone as it relies on the user's environment and so on, that's why I try to avoid it when I can.

I'll do it sometime in the future probably, but not having downloadable docs for the packages makes it a lot more difficult.

**Comment by retrography** [comment]
@Kapeli, that's what @MrLoh is suggesting here. Since now R has a 3rd party service (RDocumentation.org), the docs don't need to be generated from source anymore. RDocumentation is doing all the hard work, and the conversion will be between their pre-cleansed documents and Dash Docset. 

But I am glad anyway that you already see the feature somewhere down the roadmap.

**Comment by Kapeli** [comment]
Ah. So it's possible to download offline-working HTML docs from RDocumentation.org?

**Comment by retrography** [comment]
@Kapeli It is theoretically possible, but that is what we would like to hear from @ludov04 as well. He doesn't seem to be against it, but it seems they didn't judge it feasible as they though making dash docsets would necessarily involve systematically creating and storing recent versions of docset files for all packages. What I am trying to convey here is that given their clean HTML document set, the conversion can be done on-the-fly. Have a look for yourself. For instance, here are the docs for the 'readr' package: https://www.rdocumentation.org/packages/readr. They have done an awesome job!

**Comment by ron-wolf** [comment]
Sorry to bump an old issue, but is it settled what work would be required to get this off the ground? Do the docs need to be converted for use in Dash? Does Dash need an API endpoint for it to fetch the docs from? I’m not familiar with this besides noticing references to XML feeds when searching the web for a solution.

@Kapeli Could I bother you for some pointers?

**Comment by Kapeli** [comment]
What I need in order to support docs for R packages in Dash is:

1. A way to search for packages
2. A way to get the available versions for a package
3. A way to download the HTML docs for a package and version

There's no need to convert the HTML docs in any way, I can process that on my end.

**Comment by ron-wolf** [comment]
@Kapeli Wow, thanks for the reply, and especially for being willing to process things on your end! I've included the API endpoints I found below the break. Let me know if they need to be reformatted, or if I can help write the code necessary to retrieve/convert the docs.

---

<details>
  <summary>&nbsp;<strong>Searching for a package</strong></summary>
  
  <br/>
  
  `https://api.rdocumentation.org/search_functions?q=$NAME&page=$PAGE&latest=1`
  
  Variables:
  * `$NAME` &ndash; package name
  * `$PAGE` &ndash; page number of results (1-based)
  
  <br/>
</details>

<details>
  <summary>&nbsp;<strong>Getting the available versions of a package</strong></summary>
  
  <br/>
  
  `https://www.rdocumentation.org/packages/$NAME`
  
  Variables:
  * `$NAME` &ndash; package name
  
  Response format:
  * Redirects to page for latest package version
  * All versions are under `<select>` tag with `#version` id
  
  <br/>
</details>

<details>
  <summary>&nbsp;<strong>Downloading docs for a package and version</strong></summary>
  
  <br/>
  
  `https://www.rdocumentation.org/packages/$NAME/versions/$VERSION`
  
  Variables:
  * `$NAME` &ndash; package name
  * `$VERSION` &ndash; package version
  
  Response format:
  * Index page is in `<article>` tag
  * Links to functions are under `<div>` tag with `.css-1e0w0dg` class
  
  <br/>
</details>

**Comment by Kapeli** [comment]
Thanks! I think I have everything I need. I'll try to allocate time to work on this ASAP.

**Comment by ron-wolf** [comment]
Got it! And again, please don’t hesitate to reach out if you’d like to delegate, that’s how open source works at its best :)
