### ISSUE TITLE
Searching for "network" or "graph" should find the igraph package

### ISSUE THREAD

**Issue by krlmlr** [datacamp/rdocumentation-app#74]
Moved from https://github.com/datacamp/Rdocumentation/issues/11.

http://www.rdocumentation.org/search?q=network

Reason: Both keywords are part of the package's description (or details), and it seems to be way more popular than the "network" package which appears as top result.

CC @gaborcsardi.

**Comment by ludov04** [comment]
Hey, 

Not sure if it should appear before as "network" package is a direct match. IMO, the package name should definitely have more importance than the description field. 

However, igraph should definitely appear earlier. The problem is that a lot of functions of popular or base packages are also relevant. We are splitting the search results in two columns (topics and packages) (see #56 ) to have more clear and relevant result.

igraph should then appear as one of the top packages.

**Comment by ludov04** [comment]
igraph now appears in the first page:
http://www.rdocumentation.org/search?q=network
